### ISSUE TITLE
Importing module in child modules without configuring it

### ISSUE THREAD

**Issue by destructor465** [vh13294/nestjs-url-generator#1]
Hello,

At the moment you have to import `UrlGeneratorModule.forRoot/forRootAsync` for each module you're using it in. Would it be possible to import it using `forRoot/forRootAsync` once in like `AppModule` and then in all child modules import it adding simple `UrlGeneratorModule` to the imports list, so you don't have to configure it every time.

**Comment by vh13294** [comment]
If you import at AppModule, the service will be available globally, you could just import the service (not module) and inject it where you need it.

**Comment by destructor465** [comment]
If I try to import service it throws:
`Nest can't resolve dependencies of the UrlGeneratorService (?, ApplicationConfig). Please make sure that the argument UrlGeneratorModuleOptions at index [0] is available in the UrlGeneratorService context.`

**Comment by vh13294** [comment]
Sorry, my mistake.

Yeah there is an error, I may have to look into it.

**Comment by vh13294** [comment]
I just made a quick fix.

c4f0d9503be1bdbc5364b4a6c267819a267c39af

You can update to the latest version 0.0.5

**Comment by destructor465** [comment]
Thanks, it works now.
