### ISSUE TITLE
Update peer dependencies to Nest 9.x

### ISSUE THREAD

**Issue by Tomas2D** [vh13294/nestjs-url-generator#11]

**Comment by ebuildy** [comment]
Hey Tomas, do u think this is can be done in a few days? (just to know if I can wait or fork), many thanks

**Comment by Tomas2D** [comment]
Hello, it can be done easily. I have created a PR for that: #13

**Comment by Tomas2D** [comment]
ping @vh13294

**Comment by Tomas2D** [comment]
ping @vh13294
