### ISSUE TITLE
ApplicationConfig dependency

### ISSUE THREAD

**Issue by koekaverna** [vh13294/nestjs-url-generator#8]
Hello, first of all thank you for making this project.

I have a problem in my project with `ApplicationConfig` when running code in `cli` with `nestjs-console`. There is no such service. 
It will be nice if there was a possibility to configure 'prefix' in the same way as `appUrl` and use `ApplicationConfig.getGlobalPrefix()` only when it's not set

I can make PR if you want.

**Comment by vh13294** [comment]
Can you include the prefix in appUrl?
If not ! I am happy to receive a pull request!

**Comment by koekaverna** [comment]
> Can you include the prefix in appUrl?  

There is error while access `getGlobalPrefix()` on `undefined`

Please check this PR https://github.com/vh13294/nestjs-url-generator/pull/9
